version: "3"

services:

  luminesce-sdk-csharp-preview-build:
    build: .
    container_name: luminesce-sdk-csharp-preview-build
    image: finbourne/luminesce-sdk-csharp-preview-build
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_LUMINESCE_API_URL
      - FBN_APP_NAME
    volumes:
      - .:/usr/src